//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WebStore.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WebStoreDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WebStoreDBEntities object using the connection string found in the 'WebStoreDBEntities' section of the application configuration file.
        /// </summary>
        public WebStoreDBEntities() : base("name=WebStoreDBEntities", "WebStoreDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WebStoreDBEntities object.
        /// </summary>
        public WebStoreDBEntities(string connectionString) : base(connectionString, "WebStoreDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WebStoreDBEntities object.
        /// </summary>
        public WebStoreDBEntities(EntityConnection connection) : base(connection, "WebStoreDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Item> Items
        {
            get
            {
                if ((_Items == null))
                {
                    _Items = base.CreateObjectSet<Item>("Items");
                }
                return _Items;
            }
        }
        private ObjectSet<Item> _Items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemPrice> ItemPrices
        {
            get
            {
                if ((_ItemPrices == null))
                {
                    _ItemPrices = base.CreateObjectSet<ItemPrice>("ItemPrices");
                }
                return _ItemPrices;
            }
        }
        private ObjectSet<ItemPrice> _ItemPrices;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItems(Item item)
        {
            base.AddObject("Items", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemPrices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemPrices(ItemPrice itemPrice)
        {
            base.AddObject("ItemPrices", itemPrice);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebStoreDBModel", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="stock">Initial value of the Stock property.</param>
        public static Item CreateItem(global::System.Int32 id, global::System.String title, global::System.Int32 stock)
        {
            Item item = new Item();
            item.ID = id;
            item.Title = title;
            item.Stock = stock;
            return item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Stock
        {
            get
            {
                return _Stock;
            }
            set
            {
                OnStockChanging(value);
                ReportPropertyChanging("Stock");
                _Stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stock");
                OnStockChanged();
            }
        }
        private global::System.Int32 _Stock;
        partial void OnStockChanging(global::System.Int32 value);
        partial void OnStockChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebStoreDBModel", Name="ItemPrice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemPrice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemPrice object.
        /// </summary>
        /// <param name="priceID">Initial value of the PriceID property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="entered">Initial value of the Entered property.</param>
        public static ItemPrice CreateItemPrice(global::System.Int32 priceID, global::System.Int32 id, global::System.Double price, global::System.DateTime entered)
        {
            ItemPrice itemPrice = new ItemPrice();
            itemPrice.PriceID = priceID;
            itemPrice.ID = id;
            itemPrice.Price = price;
            itemPrice.Entered = entered;
            return itemPrice;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PriceID
        {
            get
            {
                return _PriceID;
            }
            set
            {
                if (_PriceID != value)
                {
                    OnPriceIDChanging(value);
                    ReportPropertyChanging("PriceID");
                    _PriceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PriceID");
                    OnPriceIDChanged();
                }
            }
        }
        private global::System.Int32 _PriceID;
        partial void OnPriceIDChanging(global::System.Int32 value);
        partial void OnPriceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Double _Price;
        partial void OnPriceChanging(global::System.Double value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Entered
        {
            get
            {
                return _Entered;
            }
            set
            {
                OnEnteredChanging(value);
                ReportPropertyChanging("Entered");
                _Entered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Entered");
                OnEnteredChanged();
            }
        }
        private global::System.DateTime _Entered;
        partial void OnEnteredChanging(global::System.DateTime value);
        partial void OnEnteredChanged();

        #endregion
    
    }

    #endregion
    
}
